Repository Gyeongdan/gyeongdan-server-spring, pull requests merged in 2024-07, with the labels that each got.

#11 카카오 로그인 구현
  build.gradle.kts
  src/main/java/gyeongdan/common/RestClientConfig.java
  src/main/java/gyeongdan/user/controller/KakaoOauthController.java
  src/main/java/gyeongdan/user/domain/Users.java
  src/main/java/gyeongdan/user/dto/KakaoLoginResponseDTO.java
  src/main/java/gyeongdan/user/dto/KakaoProfile.java
  src/main/java/gyeongdan/user/dto/KakaoTokenInfo.java
  src/main/java/gyeongdan/user/exception/UserException.java
  src/main/java/gyeongdan/user/repository/UserManageRepository.java
  src/main/java/gyeongdan/user/service/KakaoOauthService.java
  src/main/java/gyeongdan/user/service/UserManageService.java
  src/main/java/gyeongdan/util/CustomException.java
  src/main/java/gyeongdan/util/ErrorCode.java
  src/main/java/gyeongdan/util/ErrorResponse.java
  src/main/java/gyeongdan/util/JwtUtil.java
  src/main/java/gyeongdan/util/LoginAspect.java
  src/main/java/gyeongdan/util/LoginAuthenticated.java
Labels: Feature

#13 기사 관련 API 작업
  build.gradle.kts
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/domain/Article.java
  src/main/java/gyeongdan/article/dto/ArticleUpdateRequest.java
  src/main/java/gyeongdan/article/repository/ArticleRepository.java
  src/main/java/gyeongdan/article/service/ArticleService.java
Labels: Feature

#17 GPT 응답값 DB에 저장하기, 경제 용어 질문 키워드 분석 후 답변하는 로직 구현하기
  README.md
  build.gradle.kts
  src/main/java/gyeongdan/ChatBot/controller/ChatBotController.java
  src/main/java/gyeongdan/ChatBot/controller/EconomicTermCRUDController.java
  src/main/java/gyeongdan/ChatBot/controller/EconomicTermController.java
  src/main/java/gyeongdan/ChatBot/model/EconomicTerm.java
  src/main/java/gyeongdan/ChatBot/model/GptResponse.java
  src/main/java/gyeongdan/ChatBot/repository/ChatBotRepository.java
  src/main/java/gyeongdan/ChatBot/repository/EconomicTermRepository.java
  src/main/java/gyeongdan/ChatBot/service/ChatBotService.java
  src/main/java/gyeongdan/ChatBot/service/EconomicTermCRUDService.java
  src/main/java/gyeongdan/ChatBot/service/EconomicTermService.java
  src/main/java/gyeongdan/ChatBot/service/WordAnalysisService.java
  src/main/java/gyeongdan/ChatBot/utils/CmmUtil.java
Labels: Feature

#22 경단어 응답 고도화
  src/main/java/gyeongdan/chatBot/term/controller/EconomicTermController.java
  src/main/java/gyeongdan/chatBot/term/service/EconomicTermService.java
  src/main/java/gyeongdan/chatBot/term/service/MorphologicalAnalysisService.java
Labels: Feature

#24 사용자의 질문에서 키워드 뽑는 과정 고도화하기
  src/main/java/gyeongdan/chatBot/term/service/EconomicTermService.java
  src/main/java/gyeongdan/chatBot/term/service/EnglishWordAnalysisService.java
  src/main/java/gyeongdan/chatBot/term/service/MorphologicalAnalysisService.java
Labels: Feature

#27 Spring 서버 CICD 구축
  .github/workflows/deploy-ecs.yml
  Dockerfile
  src/main/java/gyeongdan/article/domain/Article.java
  src/main/java/gyeongdan/user/domain/Users.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  tf-staging.json
Labels: Feature

#26 경단 소개 - 자주 묻는 질문들 API 구현
  src/main/java/gyeongdan/chatBot/introduce/controller/FAQController.java
  src/main/java/gyeongdan/chatBot/introduce/model/FAQ.java
  src/main/java/gyeongdan/chatBot/introduce/repository/FAQRepository.java
  src/main/java/gyeongdan/chatBot/introduce/service/FAQService.java
Labels: Feature

#32 기사 조회 API 수정
  src/main/java/gyeongdan/article/controller/AdminArticleController.java
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/domain/Article.java
  src/main/java/gyeongdan/article/service/ArticleService.java
  src/main/java/gyeongdan/util/GlobalExceptionHandler.java
Labels: Bug

#29 Spring 서버 CICD 구축
  .github/workflows/deploy-ecs.yml
  Dockerfile
  src/main/resources/application.yml
  src/test/java/gyeongdan/gyeongdan/GyeongdanApplicationTests.java
  tf-staging.json
Labels: Feature

#33 (기사 조회 시) 조회수 저장 및 조회수-유저 매핑 구현
  .gitignore
  src/main/.gitignore
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/domain/Article.java
  src/main/java/gyeongdan/article/domain/ArticleViewHistory.java
  src/main/java/gyeongdan/article/repository/ArticleRepository.java
  src/main/java/gyeongdan/article/repository/ArticleRepositoryImpl.java
  src/main/java/gyeongdan/article/repository/ArticleViewHistoryJpaRepository.java
  src/main/java/gyeongdan/article/service/ArticleService.java
  src/main/java/gyeongdan/chatBot/introduce/repository/FAQRepository.java
  src/main/java/gyeongdan/chatBot/introduce/service/FAQService.java
  src/main/java/gyeongdan/util/JwtUtil.java
  src/main/resources/application.properties
Labels: Feature

#35 유저별로 최신 기사 3개 불러오기
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/repository/ArticleViewHistoryJpaRepository.java
  src/main/java/gyeongdan/article/service/ArticleService.java
Labels: Feature

#37 조회 API 총정리
  src/main/java/gyeongdan/article/article/controller/AdminArticleController.java
  src/main/java/gyeongdan/article/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/article/domain/Article.java
  src/main/java/gyeongdan/article/article/dto/ArticleAllResponse.java
  src/main/java/gyeongdan/article/article/dto/ArticleDetailResponse.java
  src/main/java/gyeongdan/article/article/dto/ArticleUpdateRequest.java
  src/main/java/gyeongdan/article/article/dto/PopularArticleResponse.java
  src/main/java/gyeongdan/article/article/repository/ArticleJpaRepository.java
  src/main/java/gyeongdan/article/article/repository/ArticleRepository.java
  src/main/java/gyeongdan/article/article/repository/ArticleRepositoryImpl.java
  src/main/java/gyeongdan/article/article/service/ArticleService.java
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/domain/Article.java
  src/main/java/gyeongdan/article/related_documents/domain/ArticleRelatedDocuments.java
  src/main/java/gyeongdan/article/related_documents/repository/ArticleRelatedDocumentsRepository.java
  src/main/java/gyeongdan/article/related_documents/service/ArticleRelatedDocumentsService.java
  src/main/java/gyeongdan/article/repository/ArticleViewHistoryJpaRepository.java
  src/main/java/gyeongdan/article/view_history/domain/ArticleViewHistory.java
  src/main/java/gyeongdan/article/view_history/repository/ArticleViewHistoryJpaRepository.java
  src/main/java/gyeongdan/shortform/controller/ShortFormController.java
  src/main/java/gyeongdan/shortform/domain/ShortForm.java
  src/main/java/gyeongdan/shortform/dto/ShortFormDetailResponse.java
  src/main/java/gyeongdan/shortform/repository/ShortFormJpaRepository.java
  src/main/java/gyeongdan/shortform/service/ShortFormService.java
  src/main/java/gyeongdan/user/service/UserManageService.java
  src/main/java/gyeongdan/util/JwtUtil.java
  src/main/resources/application.properties
Labels: Feature

#42 기사 조회 API: 이미지, publishedAt 추가
  src/main/java/gyeongdan/article/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/article/domain/Article.java
  src/main/java/gyeongdan/article/article/dto/ArticleAllResponse.java
  src/main/java/gyeongdan/article/article/dto/ArticleDetailResponse.java
  src/main/java/gyeongdan/article/article/service/ArticleService.java
Labels: Feature

#47 추천 기사 API 구현
  src/main/java/gyeongdan/article/recommend/controller/RecommendController.java
  src/main/java/gyeongdan/article/recommend/domain/Recommends.java
  src/main/java/gyeongdan/article/recommend/domain/UserType.java
  src/main/java/gyeongdan/article/recommend/repository/RecommendJpaRepository.java
  src/main/java/gyeongdan/article/recommend/repository/UserTypeJpaRepository.java
  src/main/java/gyeongdan/article/recommend/service/RecommendService.java
Labels: Feature

#49 지난 인사이트 3개 조회 API 구현 (createdAt을 기준으로)
  src/main/java/gyeongdan/shortform/controller/ShortFormController.java
  src/main/java/gyeongdan/shortform/domain/ShortForm.java
  src/main/java/gyeongdan/shortform/repository/ShortFormJpaRepository.java
  src/main/java/gyeongdan/shortform/service/ShortFormService.java
Labels: Feature

#51 refactor : 가장 최신 기사 3개가 아니라 2,3,4등 기사 조회해야함!!!
  src/main/java/gyeongdan/shortform/repository/ShortFormJpaRepository.java
  src/main/java/gyeongdan/shortform/service/ShortFormService.java
Labels: enhancement

#54 유형 검사 결과 반환 구현
  build.gradle.kts
  src/main/java/gyeongdan/article/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/article/domain/Article.java
  src/main/java/gyeongdan/article/article/dto/ArticleDetailResponse.java
  src/main/java/gyeongdan/article/recommend/service/RecommendService.java
  src/main/java/gyeongdan/article/type_test/controller/TypeTestController.java
  src/main/java/gyeongdan/article/type_test/domain/UserType.java
  src/main/java/gyeongdan/article/type_test/repository/UserTypeJpaRepository.java
Labels: Feature

#61 deploy-ecs-2.yml 삭제
  .github/workflows/deploy-ecs-2.yml
Labels: Ship

#66 Spring AOP활용 JWT 토큰으로 Auth하도록 수정 및 Security Context 활용
  src/main/java/gyeongdan/article/controller/TypeTestController.java
  src/main/java/gyeongdan/article/service/RecommendService.java
  src/main/java/gyeongdan/user/controller/UserTypeController.java
  src/main/java/gyeongdan/user/domain/UserType.java
  src/main/java/gyeongdan/user/domain/UserTypeEnum.java
  src/main/java/gyeongdan/user/dto/UserTypeRecord.java
  src/main/java/gyeongdan/user/dto/UserTypeTestResult.java
  src/main/java/gyeongdan/user/repository/UserTypeJpaRepository.java
  src/main/java/gyeongdan/user/service/KakaoOauthService.java
  src/main/java/gyeongdan/user/service/UserManageService.java
  src/main/java/gyeongdan/util/annotation/LoginAspect.java
Labels: Feature

#65 이번주 인기 있는 기사 10개 조회하는 API로 리팩토링
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/repository/ArticleJpaRepository.java
  src/main/java/gyeongdan/article/repository/ArticleViewHistoryJpaRepository.java
  src/main/java/gyeongdan/article/service/ArticleService.java
  src/main/java/gyeongdan/user/domain/UserType.java
Labels: Feature

#68 유저 이름 조회 API
  src/main/java/gyeongdan/user/controller/UserController.java
  src/main/java/gyeongdan/user/service/UserManageService.java
Labels: Ship

#70 회원 조회시 프로필 사진도 가져오도록 수정
  src/main/java/gyeongdan/user/controller/UserController.java
  src/main/java/gyeongdan/user/domain/UserProfile.java
  src/main/java/gyeongdan/user/service/UserManageService.java
Labels: Feature

#73 뉴스레터 API 리팩토링하기 !!!!
  src/main/java/gyeongdan/article/controller/ArticleController.java
  src/main/java/gyeongdan/article/controller/RecommendController.java
  src/main/java/gyeongdan/article/repository/ArticleJpaRepository.java
  src/main/java/gyeongdan/article/repository/ArticleRepository.java
  src/main/java/gyeongdan/article/repository/ArticleRepositoryImpl.java
  src/main/java/gyeongdan/article/service/ArticleService.java
  src/main/java/gyeongdan/article/service/RecommendService.java
  src/main/java/gyeongdan/chatBot/term/controller/EconomicTermController.java
  src/main/java/gyeongdan/user/repository/UserTypeJpaRepository.java
  src/main/java/gyeongdan/user/service/UserManageService.java
Labels: enhancement, Bug

#74 챗봇 API 리팩토링
  src/main/java/gyeongdan/chatBot/introduce/controller/FAQController.java
  src/main/java/gyeongdan/chatBot/introduce/repository/FAQJPArepository.java
  src/main/java/gyeongdan/chatBot/introduce/service/FAQService.java
  src/main/java/gyeongdan/chatBot/term/controller/EconomicTermController.java
  src/main/java/gyeongdan/chatBot/term/service/EconomicTermService.java
Labels: enhancement, Bug
